### PR TITLE
Updated: Embedded version of the AccessControlTestModule

### PR DESCRIPTION
**Pull request by newmans99**
Based on both your and Geoff's feedback I have added back the redirect support. It was actually quite trivial and definitely is better than what I was originally thinking. Please review this and consider it for merging into your master tree. If there are concerns please let me know and I can either change the fork or publish it separately as we discussed previously.

Thanks,
Steve

### CODE REVIEW

**Comment by flautrup** [comment]
So I think this looks good, I just want to run it as well and just not look at the code before I accept the pull request.

I have one other thought, it should be possible to have a couple of examples/templates of HTML files in the project for those that want the old behaviour and those that want the iFrame version. What do you think of that?

**Comment by newmans99** [comment]
That would be fine as well. If that is the case then we should pull the user definitions into a JSON array in the config file so that the UI can be changed with a flag in the config. Otherwise they will have to change the user formats every time they change the UI format. 

Steve

**Comment by flautrup** [comment]
I have a couple of comments after I tested it:
- Some UI stuff that I think we can make after I have merged the pull request
- You are not able to login with the user at the top of the list as this will not trigger an event
- If you logout from the hub you will get an iframe in an iframe, not sure how this best can be solved.

Having multiple HTML files we can add later as a new feature.

**Comment by newmans99** [comment]
Thanks for testing. Do you want me to resolve these issues and re-pull?

Steve

**Pull request merged**
