### PR TITLE
Embedded version of the AccessControlTestModule

### PR DESCRIPTION
**Pull request by newmans99**
Fredrik,
I have modified your ACTM example to have a drop down box for users and display either the Hub or a Sheet on the same page. This demonstrates the use of the Logout method plus a few other techniques. I have also changed some of the configuration parameters and updated the Readme.md file.

Please consider merging these changes if you believe that they are useful.
Steve

### CODE REVIEW

**Comment by flautrup** [comment]
This looks good. I will have to test it out. 

The only thing that I would like to maintain is the use of the RedirectURL and targetID from the parameters of the login request. It is fine to use a configuration file but if this is used as an example of best practice the usage the parameters is better simplify configuration and allow for scenarios where you have multiple proxies connected to the same authentication module. 

Is the configuration needed for the iframe integration to work?

**Comment by newmans99** [comment]
Yes. They are needed.

Maybe I should create a separate project that is simply a branch from yours. That way they solve different needs. Thoughts?
Steve

**Comment by goldbergjeffrey** [comment]
My two cents, I think forking makes sense because of the original intent of the solution is a baseline to build from.

**Comment by flautrup** [comment]
I think what you have done is great work but I agree with Jeff that perhaps we should create a project of its own.

**Comment by newmans99** [comment]
Works for me. I will startup a new one. 

Thanks,
Steve

**Pull request closed without merging**
